package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/lykuroai/Native-LLM-Platform/gwcore"
	"github.com/lykuroai/Native-LLM-Platform/token"
)

// runInit generates gateway.yaml from discovered runtimes(discover の結果を
// そのまま設定へ落とし込む導入コマンド)。既存ファイルは --force なしでは
// 上書きしない。Runtime が見つからなくてもモデル 0 件の有効な設定を書き出し、
// モデルは後から管理画面の discover/取込か手編集で追加できる。
func runInit(args []string) int {
	var cidr string
	force := false
	for i, a := range args {
		if (a == "-cidr" || a == "--cidr") && i+1 < len(args) {
			cidr = args[i+1]
		}
		if a == "-force" || a == "--force" {
			force = true
		}
	}
	path := configPath(args)
	if _, err := os.Stat(path); err == nil && !force {
		fmt.Fprintf(os.Stderr, "%s already exists (use --force to overwrite)\n", path)
		return 2
	}

	hosts, err := gwcore.DiscoverHosts(cidr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "init: %v\n", err)
		return 2
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	fmt.Printf("scanning %d host(s) for runtimes...\n", len(hosts))
	candidates := gwcore.DiscoverRuntimes(ctx, hosts, map[string]bool{})

	seg, err := token.RandomTokenSegment(8)
	if err != nil {
		fmt.Fprintf(os.Stderr, "init: %v\n", err)
		return 1
	}
	cfg := buildInitConfig("gw-"+strings.ToLower(seg), candidates)
	if len(cfg.Models) == 0 {
		if len(candidates) == 0 {
			fmt.Println("no runtimes found — generating a config with an empty model list")
		} else {
			fmt.Println("runtimes were found but none reported a loaded model — generating a config with an empty model list")
		}
	}

	// すぐ使える設定にするため Virtual Key も同時発行(原文は一度きり表示)
	plainKey, keyHash, err := gwcore.GenerateVirtualKey()
	if err != nil {
		fmt.Fprintf(os.Stderr, "init: %v\n", err)
		return 1
	}
	cfg.Auth.VirtualKeys = []gwcore.VirtualKeyDef{{
		ID: "vk-default", Name: "generated by init", KeyHash: keyHash,
	}}
	if err := cfg.Validate(); err != nil {
		fmt.Fprintf(os.Stderr, "init: generated config is invalid: %v\n", err)
		return 1
	}

	raw, err := yaml.Marshal(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "init: %v\n", err)
		return 1
	}
	header := fmt.Sprintf("# generated by private-gateway init (%s)\n# 検証: private-gateway config validate -config %s\n",
		time.Now().UTC().Format(time.RFC3339), path)
	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			fmt.Fprintf(os.Stderr, "init: %v\n", err)
			return 1
		}
	}
	if err := os.WriteFile(path, append([]byte(header), raw...), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "init: write failed: %v\n", err)
		return 1
	}

	fmt.Printf("\nwrote %s (gateway %s, models %d)\n", path, cfg.Gateway.ID, len(cfg.Models))
	for _, m := range cfg.Models {
		fmt.Printf("  - %-32s %-18s %s (%s)\n", m.LogicalName, m.Runtime, m.Endpoint, m.PhysicalModel)
	}
	fmt.Printf("\nvirtual key (share securely, shown once):\n  %s\n", plainKey)
	fmt.Printf("\nnext steps:\n  private-gateway serve -config %s\n", path)
	fmt.Printf("  curl http://127.0.0.1%s/v1/models -H \"Authorization: Bearer <key>\"\n", cfg.Gateway.Listen)
	if len(cfg.Models) == 0 {
		fmt.Println("\nadd models later:")
		fmt.Println("  - start your runtime (native-engine/vLLM/Ollama/TGI) and re-run: private-gateway init --force")
		fmt.Printf("  - or use the admin UI discover/adopt: LYKURO_ADMIN_ENABLED=1 private-gateway serve -config %s\n", path)
		fmt.Printf("  - or edit %s by hand (see config/gateway.example.yaml)\n", path)
	}
	return 0
}

var logicalNameRe = regexp.MustCompile(`[^a-z0-9._-]+`)

// sanitizeLogicalName derives a logical model name from a physical name
// (例: "llama3:8b" → "llama3-8b"、"meta-llama/Llama-3-8B" → "meta-llama-llama-3-8b")。
func sanitizeLogicalName(physical string) string {
	name := logicalNameRe.ReplaceAllString(strings.ToLower(physical), "-")
	name = strings.Trim(name, "-")
	if name == "" {
		return "model"
	}
	return name
}

// buildInitConfig maps discovered candidates to a gateway config。
// (endpoint × 検出モデル) ごとに 1 エントリ。logical 名は物理名から導出し、
// 衝突時は連番を付ける。モデル報告のない endpoint は採用しない。
func buildInitConfig(gatewayID string, candidates []gwcore.RuntimeCandidate) *gwcore.Config {
	cfg := &gwcore.Config{
		SchemaVersion: "1",
		Gateway:       gwcore.GatewaySection{ID: gatewayID, Listen: ":8443"},
	}
	used := map[string]bool{}
	for _, c := range candidates {
		for _, physical := range c.Models {
			logical := sanitizeLogicalName(physical)
			for n := 2; used[logical]; n++ {
				logical = fmt.Sprintf("%s-%d", sanitizeLogicalName(physical), n)
			}
			used[logical] = true
			cfg.Models = append(cfg.Models, gwcore.ModelDef{
				LogicalName:   logical,
				Runtime:       c.Runtime,
				Endpoint:      strings.TrimRight(c.Endpoint, "/"),
				PhysicalModel: physical,
			})
		}
	}
	return cfg
}
